version: '3'
services:
  weather-app:
    container_name: weather-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - weather-app-net
    depends_on:
      - redis
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    networks:
      - weather-app-net
networks:
  weather-app-net:
    driver: bridge
