apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: weather
  labels:
    app: weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-app
  strategy: {}
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: kimimtz/weather-app:v1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: weather-app-config
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: weather-app-config
            - name: REDIS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: REDIS_EXPIRATION
                  name: weather-app-config
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  key: API_KEY
                  name: weather-app-config
            - name: CITY
              valueFrom:
                configMapKeyRef:
                  key: CITY
                  name: weather-app-config
            
